name: wasp-upload-action
description: Upload Simba scripts to waspscripts.com
author: Torwent
branding: upload

inputs:
  SB_URL:
    description: Supabase URL
    required: true
    type: string
  SB_ANON_KEY:
    description: Supabase ANON Key
    required: true
    type: string
  EMAIL:
    description: User email
    required: true
    type: string
  PASSWORD:
    description: User password
    required: true
    type: string
  PATH:
    default: /
    description: Directory path where the files are located
    required: false
    type: string
  SCRIPTS:
    description: Script ID and File to upload. The syntax is "SCRIPT_ID1=SCRIPT_FILE1\nSCRIPT_ID2=SCRIPT_FILE2"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - runs:
        using: node16
        main: dist/index.js
