name: wasp-upload-action
description: Upload Simba scripts to waspscripts.com
author: Torwent
branding: upload

inputs:
  SB_URL:
    description: Supabase URL
    required: true
    type: string
  SB_ANON_KEY:
    description: Supabase ANON Key
    required: true
    type: string
  EMAIL:
    description: User email
    required: true
    type: string
  PASSWORD:
    description: User password
    required: true
    type: string
  ONLY_MODIFIED:
    default: true
    description: Wether to upload everything or only the modified simba scripts
    required: false
    type: boolean
  PATH:
    default: ""
    description: Directory path where the files are located
    required: false
    type: string
  SCRIPTS:
    description: Script ID and simba file links. The syntax is "SCRIPT_ID1=SCRIPT_FILE1\nSCRIPT_ID2=SCRIPT_FILE2"
    required: true
    type: string
  MODIFIED_FILES:
    default: ""
    description: JSON Input of the modified files
    required: false
    type: string
runs:
  using: node16
  main: dist/index.js
